version: '3.8'

services:
  whatsapp-bot:
    build: .
    container_name: bot-barbearia
    restart: unless-stopped
    ports:
      - "80:3000"  # ✅ MUDANÇA: Porta 80 para acesso direto via IP/domínio
    volumes:
      - ./session_data:/usr/src/app/.wwebjs_auth
      - ./logs:/usr/src/app/logs
      # ✅ REMOVIDO: Volume público (arquivos já estão na imagem)
    environment:
      - NODE_ENV=production
      - PORT=3000
    # Configurações específicas para Puppeteer
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    # Configuração de memória
    mem_limit: 1g
    memswap_limit: 1g
    # Healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
